security:
    encoders:
        HHS\KVP\KVPBackendBundle\Entity\User: md5

    providers:
            chain_provider:
                chain:
                    providers: fr3d_ldapbundle

            fr3d_ldapbundle:
                id: fr3d_ldap.security.user.provider

    role_hierarchy:
        ROLE_LEHRER: ROLE_SCHUELER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured:
            pattern: ^/
            anonymous: ~
            stateless:  true
            fr3d_ldap_httpbasic: ~