security:
    encoders:
        AcmeBundle\Acme\User\LdapUser: md5

    providers:
        chain_provider:
            chain:
                providers: fr3d_ldapbundle

        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

        #fos_userbundle:
        #    id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            fr3d_ldap_httpbasic: ~