security:

    encoders:
        IMAG\LdapBundle\User\LdapUser: md5

    providers:
        ldap:
            id: imag_ldap.security.user.provider

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            imag_ldap: ~
            http_basic: ~

imag_ldap:
    client:
        host: 172.20.10.7
        port: 389
        version: 3 # Optional
        username: cn=admin,dc=test,dc=com
        password: admin # Optional
        #network_timeout: 10 # Optional
        #referrals_enabled: true # Optional
        #bind_username_before: true # Optional
        skip_roles: false # Optional

    user:
        base_dn: ou=People,dc=test,dc=com
        filter: (&(ObjectClass=Person)) #Optional
        name_attribute: uid
    role:
        base_dn: ou=group,dc=test,dc=com
        #filter: (ou=group) #Optional
        name_attribute: cn
        user_attribute: memberUid
        user_id: username
